language: rust
sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      rust: nightly
    - os: osx
      osx_image: xcode8
      rust: nightly

install: |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    apt-get install git curl g++ autotools
    git clone https://github.com/nodejs/node.git
    cd node
    ./configure
    make -j 4
  elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew reinstall --HEAD nodejs
  fi


script:
  - cd tests
  - npm test
