language: rust
sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      rust: nightly
      node_js: head
    - os: osx
      osx_image: xcode8
      rust: nightly
      node_js: head

install: |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    git clone https://github.com/nodejs/node.git
    pushd node
    ./configure
    make -j 4
    sudo make install
    popd
  elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew reinstall -v --HEAD nodejs
  fi


script:
  - nvm use system
  - cd tests
  - npm test
